# Generated by Django 3.2.16 on 2023-03-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_id',
        ),
    ]
