# Generated by Django 3.2.16 on 2023-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230319_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
